FROM ubuntu:22.04

WORKDIR /mydir

RUN apt-get update && apt-get install -y curl python3
RUN curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
RUN chmod a+x /usr/local/bin/yt-dlp

# Create the appuser
RUN useradd -m appuser

# Change the owner of current dir to appuser
RUN chown appuser .

# Now we can change the user
USER appuser

ENTRYPOINT ["/usr/local/bin/yt-dlp"]
