version: '3.8'

services:
  cache:
    image: redis:7.2.4
    restart: always
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build:
      context: ./example-backend/
      dockerfile: ./Dockerfile
    container_name: backend-project
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=cache
    depends_on:
      - cache

  frontend:
    build:
      context: ./example-frontend/
      dockerfile: ./Dockerfile
    container_name: frontend-project
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - backend
