version: '3.8'

services:
  backend:
    build:
      context: ./example-backend/
      dockerfile: ./Dockerfile
    container_name: backend-project
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./example-frontend/
      dockerfile: ./Dockerfile
    container_name: frontend-project
    ports:
      - 5000:5000
