FROM node:16.20.2

# Change the working directory
WORKDIR /usr/src/app

# Copy the files required for dependencies to be installed
COPY package*.json ./

# Install the dependencies
RUN npm install && \
    npm install -g serve

# Copy all of the source code
COPY . .

# Set build-time variables
ARG REACT_APP_BACKEND_URL="http://localhost:8000"

# Set the environment variables
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

# 1. Build the static files
# 2. Create the appuser with home directory
# 3. Remove apt source lists
RUN npm run build && \
    useradd -m appuser && \
    rm -rf /var/lib/apt/lists/*

# Switch to the appuser
USER appuser

# Expose port 5000
EXPOSE 5000

# Serve the static files
CMD ["serve", "-s", "-l", "5000", "build"]
